config/routes.rb
Rails.application.routes.draw do
	get "/users/:user_id/articles", to: "users#index", as: "user_articles"
  get '/articles/compare', to: "articles#compare", as: "compare"

  get '/topics/crawl', to: "topics#crawl", as: "crawl"
  resources :users do
    resources :articles, shallow: true
  end
   resources :topics do
    resources :articles, shallow: true
  end

 	resources :resets, only: [:new, :create]

	root "articles#index"
	get '/articles', to: "articles#index"

	get '/about', to: "static#about", as: "about"

	get '/resets/:token', to: "resets#edit", as: "reset"
	patch '/resets/:token', to: "resets#update"

	get 'login', to: "sessions#login", as: "login"
	post 'login', to: "sessions#attempt_login"

	get '/signup', to: "sessions#signup", as: 'signup'
	post '/signup', to: "sessions#create"

	delete 'logout', to: "sessions#logout", as: "logout"
 
# 	 user_articles GET    /users/:user_id/articles(.:format)     articles#index
#                  POST   /users/:user_id/articles(.:format)     articles#create
# new_user_article GET    /users/:user_id/articles/new(.:format) articles#new
#     edit_article GET    /articles/:id/edit(.:format)           articles#edit
#          article GET    /articles/:id(.:format)                articles#show
#                  PATCH  /articles/:id(.:format)                articles#update
#                  PUT    /articles/:id(.:format)                articles#update
#                  DELETE /articles/:id(.:format)                articles#destroy
#            users GET    /users(.:format)                       users#index
#                  POST   /users(.:format)                       users#create
#         new_user GET    /users/new(.:format)                   users#new
#        edit_user GET    /users/:id/edit(.:format)              users#edit
#             user GET    /users/:id(.:format)                   users#show
#                  PATCH  /users/:id(.:format)                   users#update
#                  PUT    /users/:id(.:format)                   users#update
#                  DELETE /users/:id(.:format)                   users#destroy
#           resets POST   /resets(.:format)                      resets#create
#        new_reset GET    /resets/new(.:format)                  resets#new
#             root GET    /                                      articles#index
#         articles GET    /articles(.:format)                    articles#index
# articles_compare GET    /articles/compare(.:format)            articles#compare
#            reset GET    /resets/:token(.:format)               resets#edit
#                  PATCH  /resets/:token(.:format)               resets#update
#            login GET    /login(.:format)                       sessions#login
#                  POST   /login(.:format)                       sessions#attempt_login
#           signup GET    /signup(.:format)                      sessions#signup
#                  POST   /signup(.:format)                      sessions#create
#           logout DELETE /logout(.:format)                      sessions#logout
 end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
  belongs_to :topic

     validates :url, presence: true
     has_many :contexts
     has_many :keywords

     puts "*"*100

     def self.this_shit(someurl)
       encodedshit = URI.encode(someurl)
       url = URI.parse("http://api.diffbot.com/v3/article?token=#{ENV['DIFFBOT_KEY']}&url=#{encodedshit}")
       req = Net::HTTP::Get.new(url.to_s)
       res = Net::HTTP.start(url.host, url.port) {|http|
       http.request(req)
       }

       diffbot_hash = JSON.parse(res.body)

       puts 
       if diffbot_hash['error']
          self.dieeeeee
     end
     end

	# 'http://www.foxnews.com/us/2015/08/04/suspect-memphis-police-officer-killed-charged-murder/?intcmp=hpbt2'
     # "http://www.bbc.com/culture/story/20150804-comedy-in-the-age-of-outrage-when-jokes-go-too-far"
     # "http://www.foxnews.com/us/2015/08/04/suspect-memphis-police-officer-killed-charged-murder/"

     def save_content
          diffbotkey1 = ENV['DIFFBOT_KEY']
          url = URI.parse("http://api.diffbot.com/v3/article?token=#{diffbotkey1}&url=#{self.url}")
          req = Net::HTTP::Get.new(url.to_s)
          res = Net::HTTP.start(url.host, url.port) {|http|
               http.request(req)
          }
          diffbot_hash = JSON.parse(res.body)
          text      = diffbot_hash["objects"][0]["text"]
          source    = diffbot_hash["objects"][0]["siteName"]  
          image     = diffbot_hash["objects"][0]["images"][0]["url"]
          title     = diffbot_hash["objects"][0]["title"]
          # author may not work everytime
          author    = diffbot_hash["objects"][0]["author"]
          date      = diffbot_hash["objects"][0]["date"] 
     
          unless date
               date = diffbot_hash["objects"][0]["estimatedDate"]     
          end  
        
          self.update(raw_html: raw_html, text: text, author: author, title: title, date_published: date, image: image, source: source)
          

	end

     def save_sentiment
          AlchemyAPI.key = ENV['ALCHEMY_KEY']
          sentiments_api = AlchemyAPI.search(:sentiment_analysis, text: self.text)
          score = sentiments_api["score"].to_f
          relevance = sentiments_api["type"]
          self.update(score: score, relevance: relevance)
     end

     def save_context
          AlchemyAPI.key = ENV['ALCHEMY_KEY']
          context_api = AlchemyAPI.search(:concept_tagging, text: self.text)
          context_api.each do |c|
               relevance = c["relevance"].to_f
               text = c["text"]
               self.contexts.create(text: text, relevance: relevance)
          end
     end

     def save_keywords
          AlchemyAPI.key = ENV['ALCHEMY_KEY']
          keywords_api = AlchemyAPI.search(:keyword_extraction, text: self.text)
          keywords_api.each do |d|
               relevance = d["relevance"].to_f
               text = d["text"]
               self.keywords.create(text: text, relevance: relevance)
          end
     end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @user = User.find_by_id(session[:user_id])
  	@topics = Topic.all

  end

  def show
  	@article = Article.find_by_id(params[:id])
  end
  
  def new
   	@user = User.find_by_id(session[:user_id])
  	@article = @user.articles.new 
  end

  def create
    @user = User.find_by_id(session[:user_id])
   	@article = @user.articles.create article_params
    if @article
      ChartsWorker.perform_async(@article.id)
      redirect_to user_articles_path(session[:user_id]), flash: {success: "Created!"}
    else
      redirect_to new_user_article_path, flash: {error: @article.errors.full_messages}
    end
  end

  def compare
    @user = User.find_by_id(session[:user_id])
    @articles = Article.find(params[:article_ids])
    @score = 0
    @articles.each do |article|
      @score += article.score.to_f
    end
    @score /= @articles.length
  end

  def crawl
    @user = User.find_by_id(session[:user_id])
    x = params[:q]
    url = x
     doc = Mechanize.new
    # # doc.get("http://www.msnbc.com/")
    # doc.get("http://www.cnn.com/")
    # doc.page.forms

    # #yahoo form = doc.page.forms.first
    # form = doc.page.form("headerSearch")

    # #yahoo form.p = x

    # form.fields[0].value = x
    # y = form.submit
    # doc1 = Nokogiri::HTML(doc.page.body)
    # binding.pry

    
    # doc.page.links
    # for cnn break it down to get individual articles
    #need 2check for an empty article and remove if blank!

    page = "http://searchapp.cnn.com/search/query.jsp?page=1&npp=10&start=1&text=" + url + "&type=all&bucket=true&sort=relevance&csiID=csi1"
    require 'open-uri'
    page = URI.escape(page)
    page = page.gsub(/%20/, '%2B')
   

    doc = Nokogiri::HTML(open(page).read)
    x = JSON.parse doc.css("textarea").text

    x['results'][0].each do |result|
      

      if result['url'].starts_with? 'http://', 'https://'
        @article = @user.articles.create(url: result['url'])
      else
         
      @article = @user.articles.create(url: "http://www.cnn.com/" + result['url'])
      if @article
        ChartsWorker.perform_async(@article.id)
        end
       end
     end
     redirect_to user_articles_path(session[:user_id])

  # request = doc.get(page, :headers=>{"User-Agent" => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36"})
   
 


   
   
    # @l = doc1.css("h3[class='title'] a").map { |link| link['href'] }
    # @l.each do |link|
    #     @article = @user.articles.create(url: link)
    #     if @article
    #     ChartsWorker.perform_async(@article.id)
    #     end
    #    end
    #  redirect_to user_articles_path(session[:user_id])

    #first just get a google search result page of links with ruby.
    #for each result link create an article
  #goal: get a google page of results
  #goal: get a list of links from the results
  #goal: create a new article using above methods from each result
  #goal: check to see if an article content is blank on create and 
         #delete if so




  end

  def destroy
    @article = Article.find_by_id(params[:id])
    @article.destroy
        redirect_to user_articles_path(session[:user_id]), alert: "Article destroyed!"
  end
  
  private
    def article_params
      params.require(:article).permit(:url, :title, :text, :author, :source, :date_published, :user_id)
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/compare.html.erb
<h1>Compare</h1>
<h1>Average sentiment score: <%=@score  %></h1>
<div class= "ui relaxed grid">

<% @articles.each do |article| %>
	<div class = "ui eight wide column" id="completeShow" >
		<div id= "articleShow">
			<div id= "imageShow">
				<img src = <%=article.image %> style="height:230px"></img>
			</div>
			<div id = "titleShow">
				<%=article.title  %>
			</div>
			<div id = "titleInfo">
				<div>Author: <%=article.author  %></div>
				<div>Date: <%=article.date_published  %></div>
			</div>
		</div>
		<div id="score">
			Score: <%=article.score  %>
			<br>
			Relevance: <%=article.relevance  %>
		</div>
		
		<div id = "chart">
		How relevant are keywords to article
		<%= column_chart article.keywords.group(:text).sum(:relevance) 	%>
		</div>
		<div id = "chart">
		Concepts by context tagging
		<%= pie_chart article.contexts.group(:text).sum(:relevance	)%>
		</div>
		
		<div id = "textShow">
				<%=truncate(article.text, length: 500)%>
		</div>
	</div>
<% end %>
</div>

app/views/articles/crawl.html.erb
<div class="ui divider"></div>
  	<div id= "newArticle" class= "ui relaxed grid">
		<div id= "titleArticle" class= "four wide column"> 
			<h1>Crawl</h1>
		</div>

  		<div id ="horizontalDiv" class="ui two column very 	relaxed stackable grid">
			<div class= "ui vertical divider"></div>
		</div>

  		<div class= "ten wide column">
  		<div id="label" class="ui form">
			<%= form_for [@user,@article] do |f| %>
				<%= f.label "url" %>

				<%= f.text_field :url  %>
				<div id = "addButton" class= "ui button">
				<%= f.submit "Crawl Your Topic"  %>
				</div>
			<%end %>
		</div>
		</div>
	</div>
<div class="ui divider"></div>

app/views/articles/index.html.erb
<div id="middleBar">
	<div class="ui divider"></div>
		<div class= "ui relaxed grid">
			<div id= "pageTitle" class= "six wide column">
				<h1>User Submitted</h1>
				<h1>Articles</h1>
			</div>
			<div id ="horizontalDiv" class="ui two column very 	relaxed 	stackable grid">
				<div class= "ui vertical divider">
				explore
				</div>
			</div>
			<div id= "pageDescription" class="ui eight wide column">
					<ul>
					<li>Click on the article title for more information and data analysis.
				</li>
					<br>
					<li>Select two or more articles and click compare to compare the articles' data.
					</li>
					<br>
					<li>Compare similar topics and current events from different news sources to see their biases.</li>
					<br>
					<li>Signup or login and add your own articles and sources.
					</li>
				</ul>
			</div>
		</div>
	<div class="ui divider"></div>
</div>

<div id="compareForm">

	<%= form_tag(compare_path, {method: "get"})	 do %>
	<div id= "compareButton" > 
			<%= submit_tag "Compare", class: "ui huge violet button" %>
	</div>

	<div id= "articles" class= "ui relaxed grid">
		<% @topics.each do |topic| %>

		<%@score = 0%>
    <%topic.articles.each do |article|%>
      <%@score += article.score.to_f%>
    <%end%>
    <%if topic.articles.length > 0  %>
    <%@score /= topic.articles.length%>
    <%end  %>
	
		<div id= "article" class= "four wide column">
		
		<div id= "articleTitle" ><%= link_to topic.title, topic_path(topic) %></div>
		

		
		Average sentiment: <%=@score.to_f.round(3)  %>
		
	  		<div id="chartsAvailable">
	  		
	  			<i class="bar chart icon"></i>
	  			<i class="pie chart icon"></i>
	  			<i class="line chart icon"></i>
	  		</div>
		</div>
		<% end %>
    <% end %>

</div>

app/views/articles/new.html.erb
<div class="ui divider"></div>
  	<div id= "newArticle" class= "ui relaxed grid">
		<div id= "titleArticle" class= "four wide column"> 
			<h1>Add An Article</h1>
		</div>

  		<div id ="horizontalDiv" class="ui two column very 	relaxed stackable grid">
			<div class= "ui vertical divider"></div>
		</div>

  		<div class= "ten wide column">
  		<div id="label" class="ui form">
			<%= form_for [@user,@article] do |f| %>
				<%= f.label "url" %>

				<%= f.text_field :url  %>
				<div id = "addButton" class= "ui button">
				<%= f.submit "Add Your Article"  %>
				</div>
			<%end %>
		</div>
		</div>
	</div>
<div class="ui divider"></div>

app/views/articles/show.html.erb
<div id="completeShow">
	<div id= "articleShow">

	<%if @article.user_id.to_i == session[:user_id]  %>
	<%= link_to "destroy this article?", article_path(@article) , method: :delete, data: { confirm: 'Are you sure?' }%>
	<%end  %>
		<div id= "imageShow" class = "ui sixteen column">
			<img src = <%=@article.image %> style="height:300px"></img>
		</div>
		<div id = "titleShow">
			<%=@article.title  %>
		</div>
		<div id = "titleInfo">
			<div>Author: <%=@article.author  %></div>
			<div>Date: <%=@article.date_published  %></div>
		</div>
		<div id = "textShow">
			<%=@article.text  %>
		</div>
	
	</div>
	<div id="scoreShow">
	<% if @article.score.to_f <= -0.1 %>
		<div id="redScore">
			Score: <%=@article.score  %>
			<br>
			Relevance: <%=@article.relevance  %>
		</div>
	<% elsif @article.score.to_f <= 0%>
		<div id="orangeScore">
			Score: <%=@article.score  %>
			<br>
			Relevance: <%=@article.relevance  %>
		</div>
	<% elsif @article.score.to_f == 0%>
		<div id="whiteScore">
			Score: <%=@article.score  %>
			<br>
			Relevance: <%=@article.relevance  %>
		</div>
	<% elsif @article.score.to_f >= 0.1%>
		<div id="greenScore">
			Score: <%=@article.score  %>
			<br>
			Relevance: <%=@article.relevance  %>
		</div>
	<% else %>
		<div id="yellowScore">
			Score: <%=@article.score  %>
			<br>
			Relevance: <%=@article.relevance  %>
		</div>
	<% end %>
	</div>
	
	How relevant are keywords to article
	<div id = "chart">
	<%= column_chart @article.keywords.group(:text).sum(:relevance) %>
	</div>
	Concepts by context tagging
	<div id = "chart">
	<%= pie_chart @article.contexts.group(:text).sum(:relevance	)%>
	</div>

</div>