config/routes.rb
Rails.application.routes.draw do
	get "/users/:user_id/articles", to: "users#index", as: "user_articles"
  get '/articles/compare', to: "articles#compare", as: "compare"

  get '/topics/crawl', to: "topics#crawl", as: "crawl"
  resources :users do
    resources :articles, shallow: true
  end
   resources :topics do
    resources :articles, shallow: true
  end

 	resources :resets, only: [:new, :create]

	root "articles#index"
	get '/articles', to: "articles#index"

	get '/about', to: "static#about", as: "about"

	get '/resets/:token', to: "resets#edit", as: "reset"
	patch '/resets/:token', to: "resets#update"

	get 'login', to: "sessions#login", as: "login"
	post 'login', to: "sessions#attempt_login"

	get '/signup', to: "sessions#signup", as: 'signup'
	post '/signup', to: "sessions#create"

	delete 'logout', to: "sessions#logout", as: "logout"
 
# 	 user_articles GET    /users/:user_id/articles(.:format)     articles#index
#                  POST   /users/:user_id/articles(.:format)     articles#create
# new_user_article GET    /users/:user_id/articles/new(.:format) articles#new
#     edit_article GET    /articles/:id/edit(.:format)           articles#edit
#          article GET    /articles/:id(.:format)                articles#show
#                  PATCH  /articles/:id(.:format)                articles#update
#                  PUT    /articles/:id(.:format)                articles#update
#                  DELETE /articles/:id(.:format)                articles#destroy
#            users GET    /users(.:format)                       users#index
#                  POST   /users(.:format)                       users#create
#         new_user GET    /users/new(.:format)                   users#new
#        edit_user GET    /users/:id/edit(.:format)              users#edit
#             user GET    /users/:id(.:format)                   users#show
#                  PATCH  /users/:id(.:format)                   users#update
#                  PUT    /users/:id(.:format)                   users#update
#                  DELETE /users/:id(.:format)                   users#destroy
#           resets POST   /resets(.:format)                      resets#create
#        new_reset GET    /resets/new(.:format)                  resets#new
#             root GET    /                                      articles#index
#         articles GET    /articles(.:format)                    articles#index
# articles_compare GET    /articles/compare(.:format)            articles#compare
#            reset GET    /resets/:token(.:format)               resets#edit
#                  PATCH  /resets/:token(.:format)               resets#update
#            login GET    /login(.:format)                       sessions#login
#                  POST   /login(.:format)                       sessions#attempt_login
#           signup GET    /signup(.:format)                      sessions#signup
#                  POST   /signup(.:format)                      sessions#create
#           logout DELETE /logout(.:format)                      sessions#logout
 end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :articles
	belongs_to :user
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController


	def new
  	@topic = Topic.new 
  end

  def create
   
   	@topic = Topic.create topic_params
    if @topic
      redirect_to articles_path, flash: {success: "Created!"}
    else
      redirect_to new_topic_path, flash: {error: @article.errors.full_messages}
    end
  end

	def show
		@topic = Topic.find_by_id(params[:id])
		@articles = @topic.articles
		 @article_hash = {}
    @articles.each do |article|
      if article[:date_published]
        @article_hash[article[:date_published]] = article[:score]
      end  
    end 
	end

	def crawl
    @user = User.find_by_id(session[:user_id])
    @topic_id = params[:t]
    @topic = Topic.find_by_id(@topic_id)
    x = params[:q]
    url = x
     doc = Mechanize.new
      
    
    # # doc.get("http://www.msnbc.com/")
    # doc.get("http://www.cnn.com/")
    # doc.page.forms

    # #yahoo form = doc.page.forms.first
    # form = doc.page.form("headerSearch")

    # #yahoo form.p = x

    # form.fields[0].value = x
    # y = form.submit
    # doc1 = Nokogiri::HTML(doc.page.body)
    # binding.pry

    
    # doc.page.links
    # for cnn break it down to get individual articles
    #need 2check for an empty article and remove if blank!

    page = "http://searchapp.cnn.com/search/query.jsp?page=1&npp=10&start=1&text=" + url + "&type=all&bucket=true&sort=relevance&csiID=csi1"
    require 'open-uri'
    page = URI.escape(page)
    page = page.gsub(/%20/, '%2B')
   

    doc = Nokogiri::HTML(open(page).read)
    x = JSON.parse doc.css("textarea").text

    x['results'][0].each do |result|
      

      if result['url'].starts_with? 'http://', 'https://'
        @article = @topic.articles.create(url: result['url'])
      else
         
      @article = @topic.articles.create(url: "http://www.cnn.com/" + result['url'])
      if @article
        ChartsWorker.perform_async(@article.id)
        end
       end
   
   
     page1 = "http://www.msnbc.com/search/" + url
     doc1 = Nokogiri::HTML(open(page1).read)
     y = doc1.css(".search-result__teaser__title__link")
     
    y.each do |result|
    	 @article = @topic.articles.create(url: "http://www.msnbc.com" + result.attr('href'))
     	
      if @article
        ChartsWorker.perform_async(@article.id)
        end
       end
    end



     redirect_to topic_path(@topic)

  end

  private
    def topic_params
      params.require(:topic).permit(:title)
    end

end

app/helpers/topic_helper.rb
module TopicHelper
end

app/views/topics/new.html.erb
<div class="ui divider"></div>
  	<div id= "newArticle" class= "ui relaxed grid">
		<div id= "titleArticle" class= "four wide column"> 
			<h1>Add A Topic</h1>
		</div>

  		<div id ="horizontalDiv" class="ui two column very 	relaxed stackable grid">
			<div class= "ui vertical divider"></div>
		</div>

  		<div class= "ten wide column">
  		<div id="label" class="ui form">
			<%= form_for @topic do |f| %>
				<%= f.label "title" %>

				<%= f.text_field :title  %>
				<div id = "addButton" class= "ui button">
				<%= f.submit "Add Your Topic"  %>
				</div>
			<%end %>
		</div>
		</div>
	</div>
<div class="ui divider"></div>

app/views/topics/show.html.erb
<div id="middleBar">
	<div class="ui divider"></div>
		<div class= "ui relaxed grid">
			<div id= "pageTitle" class= "six wide column">
				<h1>View Your</h1>
				<h1>Articles</h1>
			</div>
			<div id ="horizontalDiv" class="ui two column very 	relaxed 	stackable grid">
				<div class= "ui vertical divider">
				explore
				</div>
			</div>
			<div id= "pageDescription" class="ui eight wide column">
			<ul>
				<li>Click on the article title for more information and data analysis.</li>
					<br>
					<li>Select two or more articles and click compare to compare the articles' data.</li>
					<br>
					<li>Compare similar topics and current events from different news sources to see their biases.</li>
				</ul>
			</div>
		</div>
	<div class="ui divider"></div>
</div>

<div class="chart">
	<%= line_chart(@article_hash) %>	
</div>

<%= form_tag(compare_path, {method: "get"})	 do %>

<div id= "compareButton"> 
			<%= submit_tag "Compare", class: "ui huge violet button"%>
	</div>

	<div id= "articles" class= "ui relaxed grid">
		<% @articles.each do |article| %>
		
		<div id= "article" class= "four wide column">
		<div id= "centerMe">
			<img id= "articleImage" src = <%=article.image  %> style="height:100px"  ></img>
		</div>
			<div id= "articleTitle" ><%= link_to article.title, article_path(article) %></div>
			<div id= "articleBase" >Author: <%=article.author  %></div>
			<div id= "articleBase" >Date: <%=article.date_published  %></div>
			<br>
			<div id="score">
					<% if article.score.to_f <= -0.1 %>
						<div id="redScore">
							Score: <%=article.score  %>
							<br>
							Relevance: <%=article.relevance  %>
						</div>
					<% elsif article.score.to_f <= 0%>
						<div id="orangeScore">
							Score: <%=article.score  %>
							<br>
							Relevance: <%=article.relevance  %>
						</div>
					<% elsif article.score.to_f == 0%>
						<div id="whiteScore">
							Score: <%=article.score  %>
							<br>
							Relevance: <%=article.relevance  %>
						</div>
					<% elsif article.score.to_f >= 0.1%>
						<div id="greenScore">
							Score: <%=article.score  %>
							<br>
							Relevance: <%=article.relevance  %>
						</div>
					<% else %>
						<div id="yellowScore">
							Score: <%=article.score  %>
							<br>
							Relevance: <%=article.relevance  %>
						</div>
					<% end %>
					</div>
			<br>
			<div id= "articleText" ><%=truncate(article.text, length: 350)%></div>
			<div class="ui checkbox">
	  			<input type="checkbox" name="article_ids[]" value="<%=article.id%>">
	  			<label>Select & Compare</label>
			</div>
			<div id="chartsAvailable">
  			<i class="bar chart icon"></i>
	  			<i class="pie chart icon"></i>
	  			<i class="line chart icon"></i>
	  		</div>
		</div>
			
		<% end %>
    <% end %>

</div>