config/routes.rb
Rails.application.routes.draw do
	get "/users/:user_id/articles", to: "users#index", as: "user_articles"
  get '/articles/compare', to: "articles#compare", as: "compare"

  get '/topics/crawl', to: "topics#crawl", as: "crawl"
  resources :users do
    resources :articles, shallow: true
  end
   resources :topics do
    resources :articles, shallow: true
  end

 	resources :resets, only: [:new, :create]

	root "articles#index"
	get '/articles', to: "articles#index"

	get '/about', to: "static#about", as: "about"

	get '/resets/:token', to: "resets#edit", as: "reset"
	patch '/resets/:token', to: "resets#update"

	get 'login', to: "sessions#login", as: "login"
	post 'login', to: "sessions#attempt_login"

	get '/signup', to: "sessions#signup", as: 'signup'
	post '/signup', to: "sessions#create"

	delete 'logout', to: "sessions#logout", as: "logout"
 
# 	 user_articles GET    /users/:user_id/articles(.:format)     articles#index
#                  POST   /users/:user_id/articles(.:format)     articles#create
# new_user_article GET    /users/:user_id/articles/new(.:format) articles#new
#     edit_article GET    /articles/:id/edit(.:format)           articles#edit
#          article GET    /articles/:id(.:format)                articles#show
#                  PATCH  /articles/:id(.:format)                articles#update
#                  PUT    /articles/:id(.:format)                articles#update
#                  DELETE /articles/:id(.:format)                articles#destroy
#            users GET    /users(.:format)                       users#index
#                  POST   /users(.:format)                       users#create
#         new_user GET    /users/new(.:format)                   users#new
#        edit_user GET    /users/:id/edit(.:format)              users#edit
#             user GET    /users/:id(.:format)                   users#show
#                  PATCH  /users/:id(.:format)                   users#update
#                  PUT    /users/:id(.:format)                   users#update
#                  DELETE /users/:id(.:format)                   users#destroy
#           resets POST   /resets(.:format)                      resets#create
#        new_reset GET    /resets/new(.:format)                  resets#new
#             root GET    /                                      articles#index
#         articles GET    /articles(.:format)                    articles#index
# articles_compare GET    /articles/compare(.:format)            articles#compare
#            reset GET    /resets/:token(.:format)               resets#edit
#                  PATCH  /resets/:token(.:format)               resets#update
#            login GET    /login(.:format)                       sessions#login
#                  POST   /login(.:format)                       sessions#attempt_login
#           signup GET    /signup(.:format)                      sessions#signup
#                  POST   /signup(.:format)                      sessions#create
#           logout DELETE /logout(.:format)                      sessions#logout
 end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewsBot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js" charset="utf-8"></script>
  <%= favicon_link_tag 'favicon.ico' %>

</head>
<body>
<div class="ui container">

<% flash.each do |key, value| %>
	<%= content_tag(:div, value, class: "alert#{key}")%>
<% end %>

<div id= "headingAll" class= "ui inverted masthead center aligned segment">
	<div id = "navBar" class= "ui large inverted vertical masthead center aligned segment">
		<div id= "leftMenu"  class = "item"><%= link_to "HOME", root_path %></div>
		<div id= "leftMenu" class = "item"><%= link_to "ABOUT", about_path %></div>
		<div id= "leftMenu" class = "item">
 <%@topic_id = params[:id]  %>

 <%if @topic_id   %>
		<%= form_tag(crawl_path, method: "get",class:"test" ) do %>


  <%= text_field_tag(:q,) %>

  <%= hidden_field_tag(:t, @topic_id.to_i) %>
 

 
  <%= submit_tag("Crawl") %>
<% end %>
<%end  %></div>
		
		<%if session[:user_id]%>
			<%@user = User.find_by_id(session[:user_id])  %>
			<div id = "leftMenu" class = "item"><%= link_to "NEW TOPIC", new_topic_path %></div>
			<div id= "rightMenu">
					<div   class="ui inverted button">
				<i class="child icon"></i>
				<%= link_to "My Articles", user_articles_path(session[:user_id]) %></div>
				<div  class = "ui inverted button"><%= link_to "Sign Out", logout_path, method: :delete %></div>
			</div>

		<%else%>
			<div id = "rightMenu">
				<div class = "ui inverted button"><%= link_to "Log In", login_path %></div>
				<div class = "ui inverted button"><%= link_to "Sign Up", signup_path %></div>
			</div>
		<%end%>
	</div>
	<div id= "headingMiddle" class = "ui text container">
		<h1 id = "company" class = "ui inverted header">
		Make Your Own Biases
		</h1>
		<div id= "howItWorks" class="circular ui huge violet button"> 
		<%= link_to "How It Works", about_path %>
		<i class="right arrow icon"></i>
		</div>
	</div>
</div>


<%= yield %>
</div>
</body>
</html>